In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df1 = pd.read_csv('One_year_compiled.csv')

# Ejercicio 1

In [2]:
df1.columns

Index(['timestamp', 'pCut::Motor_Torque',
       'pCut::CTRL_Position_controller::Lag_error',
       'pCut::CTRL_Position_controller::Actual_position',
       'pCut::CTRL_Position_controller::Actual_speed',
       'pSvolFilm::CTRL_Position_controller::Actual_position',
       'pSvolFilm::CTRL_Position_controller::Actual_speed',
       'pSvolFilm::CTRL_Position_controller::Lag_error', 'pSpintor::VAX_speed',
       'month', 'day', 'hour', 'sample_Number', 'mode'],
      dtype='str')

In [3]:
df1['mode'].unique()

<StringArray>
['mode1', 'mode2', 'mode5', 'mode3', 'mode4', 'mode8', 'mode6', 'mode7']
Length: 8, dtype: str

In [ ]:
df1.head()

In [5]:
# pd.set_option('display.float_format', '{:.2f}'.format)
df1.describe().round(3)

,timestamp,pCut::Motor_Torque,pCut::CTRL_Position_controller::Lag_error,pCut::CTRL_Position_controller::Actual_position,pCut::CTRL_Position_controller::Actual_speed,pSvolFilm::CTRL_Position_controller::Actual_position,pSvolFilm::CTRL_Position_controller::Actual_speed,pSvolFilm::CTRL_Position_controller::Lag_error,pSpintor::VAX_speed,month,day,hour,sample_Number
count,1062912.000,1062912.000,1062912.000,1.062912e+06,1062912.000,1.062912e+06,1062912.000,1062912.000,1062912.000,1062912.000,1062912.000,1062912.000,1062912.000
mean,4.102,-0.121,-0.000,3.371415e+08,1945.795,1.488169e+08,5367.032,0.985,1927.328,5.268,16.536,136187.983,258.874
std,2.365,0.608,0.121,5.466868e+08,4873.922,2.711355e+08,3382.194,0.344,655.905,3.503,8.488,32252.987,149.749
min,0.004,-6.560,-1.888,-2.039056e+09,-9482.574,1.936250e+05,-20.134,-0.914,0.000,1.000,1.000,81158.000,0.000
25%,2.056,-0.370,-0.022,8.626082e+07,-1908.875,2.136702e+07,3032.669,0.838,1500.000,2.000,9.000,111317.000,129.000
50%,4.104,-0.119,0.001,1.919407e+08,2595.520,7.259557e+07,4582.979,0.971,1800.000,4.000,18.000,134818.000,259.000
75%,6.152,0.255,0.024,5.691639e+08,5441.666,1.602507e+08,5823.731,1.106,2280.000,8.000,23.000,161827.000,389.000
max,8.200,3.857,2.022,1.911789e+09,17928.312,1.453671e+09,17972.023,3.568,3600.000,12.000,31.000,223249.000,518.000

# Ejercicio 3

In [6]:
df1_copia = df1.copy()
df1_copia

,timestamp,pCut::Motor_Torque,pCut::CTRL_Position_controller::Lag_error,pCut::CTRL_Position_controller::Actual_position,pCut::CTRL_Position_controller::Actual_speed,pSvolFilm::CTRL_Position_controller::Actual_position,pSvolFilm::CTRL_Position_controller::Actual_speed,pSvolFilm::CTRL_Position_controller::Lag_error,pSpintor::VAX_speed,month,day,hour,sample_Number,mode
0,0.008000,0.199603,0.027420,628392628,-920.104980,5298555,2441.235352,0.899543,1379.999756,1,4,184148.0,0.0,mode1
1,0.012000,0.281624,0.002502,628392625,-937.271118,5298565,2453.819092,0.874072,1379.999756,1,4,184148.0,0.0,mode1
2,0.016000,0.349315,-0.018085,628392621,-951.004028,5298575,2476.469727,0.879806,1379.999756,1,4,184148.0,0.0,mode1
3,0.020000,0.444450,-0.054680,628392617,-1019.668579,5298585,2501.637207,0.837500,1379.999756,1,4,184148.0,0.0,mode1
4,0.024000,0.480923,-0.042770,628392613,-1023.101807,5298595,2519.254395,0.905347,1379.999756,1,4,184148.0,0.0,mode1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062907,8.179999,-0.277697,-0.023948,194924473,7220.077148,11693928,4610.663086,0.958136,1499.999756,12,28,185909.0,518.0,mode2
1062908,8.183999,-0.285098,-0.022138,194924502,7257.842773,11693946,4618.213379,0.971821,1499.999756,12,28,185909.0,518.0,mode2
1062909,8.187999,-0.155192,-0.034412,194924531,7371.139160,11693964,4582.979004,0.981734,1499.999756,12,28,185909.0,518.0,mode2
1062910,8.191999,-0.371426,0.031594,194924560,7360.839844,11693983,4615.696777,0.987367,1499.999756,12,28,185909.0,518.0,mode2
1062911,8.195999,-0.284030,0.010178,194924590,7395.171875,11694001,4575.428711,1.000303,1499.999756,12,28,185909.0,518.0,mode2

# Ejercicio 4

In [ ]:
df1_copia.select_dtypes(include=["str"])

# Ejercicio 6

In [ ]:

df1_copia['nueva']=df1_copia["month"].values * 2
df1_copia

# Ejercicio 7

In [ ]:
df1_copia.loc[500:750, "month" : "nueva"]

In [ ]:
df1_copia.iloc[500:751, 1:5]

# Ejercicio 8

In [ ]:
consulta = df1_copia["month"] < 6
df1_copia[consulta]

In [ ]:
print(df1.info())

In [ ]:
# df1_copia = sns.load_dataset('df1_copia')

"""
sns.histplot(
    data=df, x='col',
    bins=30,              # Número de bins
    binwidth=5,           # Ancho de cada bin (alternativa a bins)
    stat='count',         # count, frequency, probability, percent, density
    kde=True,             # Superponer curva KDE
    hue='category',       # Color por categoría
    multiple='layer',     # layer, dodge, stack, fill
    element='bars',       # bars, step, poly
    cumulative=False,     # Si True, histograma acumulado
    color='steelblue',    # Color cuando no hay hue
    palette='Set2',       # Paleta de colores cuando hay hue
    alpha=0.7,            # Transparencia
    linewidth=1,          # Grosor del borde
    ax=ax                 # Axes de Matplotlib donde dibujar
)  
"""


# Histograma con KDE por especie
fig, ax = plt.subplots(figsize=(10, 6))
sns.histplot(
    bins=10,
    data=df1_copia,
    x='month',
    hue='mode',
    kde=True,
    stat='frequency',
    common_norm=False,
    alpha=0.6,
    ax=ax
)
ax.set_title('frecuencia tiempo en meses')
ax.set_xlabel('meses')
ax.set_ylabel('frecuencia')
plt.tight_layout()
plt.show()

In [ ]:
# Histograma con KDE por especie
fig, ax = plt.subplots(figsize=(10, 6))
sns.histplot(
    bins=10,
    data=df1_copia,
    x='day',
    hue='mode',
    kde=True,
    stat='frequency',
    common_norm=False,
    alpha=0.6,
    ax=ax
)
ax.set_title('frecuencia tiempo en días')
ax.set_xlabel('Dia')
ax.set_ylabel('frecuencia')
plt.tight_layout()
plt.show()

In [ ]:
# Histograma con KDE por especie
fig, ax = plt.subplots(figsize=(10, 6))
sns.histplot(
    bins=10,
    data=df1_copia,
    x='hour',
    hue='mode',
    kde=True,
    stat='frequency',
    common_norm=False,
    alpha=0.6,
    ax=ax
)
ax.set_title('frecuencia tiempo en horas')
ax.set_xlabel('horas')
ax.set_ylabel('frecuencia')
plt.tight_layout()
plt.show()

In [ ]:
# quitar decimales en las columnas 8 y 9

df1_copia = np.round(df1_copia, 2)

In [ ]:
df1_copia['pSpintor::VAX_speed'] = np.round(df1_copia['pSpintor::VAX_speed'], 2)
df1_copia['pSpintor::VAX_speed']

In [ ]:
# pasar la columna hora a otro formato

df1_copia['hour'] = df1_copia['hour'].astype(int).astype(str).str.zfill(6)

df1_copia['hour'] = df1_copia['hour'].str.replace(r'(\d{2})(\d{2})(\d{2})', r'\1/\2/\3', regex=True)

df1_copia

In [ ]:
# pasar mode a numérico

# df1_copia['mode'] = df1_copia['mode'].str.replace('Pepe', 'José', regex=False)

In [7]:
# Para responder la pregunta 3, necesitamos hacer una correlación de Pearson

matriz_correlacion = np.corrcoef(df1_copia['pCut::CTRL_Position_controller::Actual_speed'], df1_copia['pSvolFilm::CTRL_Position_controller::Actual_speed'])
matriz_correlacion[0, 1]

#  mostrar:
print(f"La sincronización entre film y corte es de: {matriz_correlacion[0, 1]}")

La sincronización entre film y corte es de: -0.3410932157447031

In [ ]:
# Definimos los umbrales (variables) según el "conocimiento experto"
umbral_averia_motor = 1.5
umbral_averia_film = 3

# Creamos la columna de avería para cada sensor por separado primero
# para ver cuál de los dos es el que está dando el problema
df1_copia['Averia_Motor'] = (df1_copia['pCut::CTRL_Position_controller::Lag_error'].abs() >= umbral_averia_motor).astype(int)
df1_copia['Averia_Film'] = (df1_copia['pSvolFilm::CTRL_Position_controller::Lag_error'].abs() >= umbral_averia_film).astype(int)

# Y la columna general que pidió la profesora (si falla uno, hay avería)
df1_copia['Averia_Total'] = ((df1_copia['Averia_Motor'] == 1) | (df1_copia['Averia_Film'] == 1)).astype(int)

# Para tu información personal (esto te dará poder mañana):
print(f"Momentos críticos en Motor: {df1_copia['Averia_Motor'].sum()}")
print(f"Momentos críticos en Film: {df1_copia['Averia_Film'].sum()}")

In [13]:
# 1. Definimos los umbrales (variables) según el "conocimiento experto"

umbral_averia_motor = 1
umbral_averia_film = 2

#1.- Creamos las columnas de avería para cada sensor, para ver cuál de los dos es el que está dando el problema.
df1_copia['Averia_Motor'] = (df1_copia['pCut::CTRL_Position_controller::Lag_error'].abs() >= umbral_averia_motor).astype(int)
df1_copia['Averia_Film'] = (df1_copia['pSvolFilm::CTRL_Position_controller::Lag_error'].abs() >= umbral_averia_film).astype(int)

# 2. La columna de "Sincronía Maestra"(desfase), muestra la diferencia entre la velocidad ideal (VAX) y la real del film

df1_copia['desfase'] = df1_copia['pSpintor::VAX_speed'] - df1_copia['pSvolFilm::CTRL_Position_controller::Actual_speed']

# 3. La columna de "Esfuerzo Relativo" se le suma el valor final por si en algún momento el del lag_error es 0
# Relacionamos Torque con Lag Error como dice el README
df1_copia['esfuerzo_relativo'] = df1_copia['pCut::Motor_Torque'] / (df1_copia['pCut::CTRL_Position_controller::Lag_error'] + 1e-5)

# 4.- La columna fatiga es un poco más compleja porque hay que hacerla movil: con un rolling_mean (https://cursos.kobalto.es/teoria/pandas-datetime#method=rolling)

# Calculamos el promedio del error absoluto en las últimas 50 muestras
# window= 50 es un estándar equilibrado, pero se puede ajustar (lo he ajustado a 100) 

df1_copia['Fatiga_Motor'] = df1_copia['pCut::CTRL_Position_controller::Lag_error'].abs().rolling(window=100).mean() 
df1_copia.fillna(value=0, inplace=True)
# https://cursos.kobalto.es/teoria/pandas-missing#method=fillna
# df1_copia.fillna(value=0, method=fill, axis=None, inplace=True, limit=None)
# no se puede añadir method, porque si coloco fill cogería el valor anterior y ese puede ser NaN, por eso se usa sólo value=0

,timestamp,pCut::Motor_Torque,pCut::CTRL_Position_controller::Lag_error,pCut::CTRL_Position_controller::Actual_position,pCut::CTRL_Position_controller::Actual_speed,pSvolFilm::CTRL_Position_controller::Actual_position,pSvolFilm::CTRL_Position_controller::Actual_speed,pSvolFilm::CTRL_Position_controller::Lag_error,pSpintor::VAX_speed,month,day,hour,sample_Number,mode,Averia_Motor,Averia_Film,desfase,esfuerzo_relativo,Fatiga_Motor
0,0.008000,0.199603,0.027420,628392628,-920.104980,5298555,2441.235352,0.899543,1379.999756,1,4,184148.0,0.0,mode1,0,0,-1061.235596,7.276797,0.000000
1,0.012000,0.281624,0.002502,628392625,-937.271118,5298565,2453.819092,0.874072,1379.999756,1,4,184148.0,0.0,mode1,0,0,-1073.819336,112.091907,0.000000
2,0.016000,0.349315,-0.018085,628392621,-951.004028,5298575,2476.469727,0.879806,1379.999756,1,4,184148.0,0.0,mode1,0,0,-1096.469971,-19.325362,0.000000
3,0.020000,0.444450,-0.054680,628392617,-1019.668579,5298585,2501.637207,0.837500,1379.999756,1,4,184148.0,0.0,mode1,0,0,-1121.637451,-8.129703,0.000000
4,0.024000,0.480923,-0.042770,628392613,-1023.101807,5298595,2519.254395,0.905347,1379.999756,1,4,184148.0,0.0,mode1,0,0,-1139.254639,-11.246929,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062907,8.179999,-0.277697,-0.023948,194924473,7220.077148,11693928,4610.663086,0.958136,1499.999756,12,28,185909.0,518.0,mode2,0,0,-3110.663330,11.600696,0.027043
1062908,8.183999,-0.285098,-0.022138,194924502,7257.842773,11693946,4618.213379,0.971821,1499.999756,12,28,185909.0,518.0,mode2,0,0,-3118.213623,12.883750,0.027256
1062909,8.187999,-0.155192,-0.034412,194924531,7371.139160,11693964,4582.979004,0.981734,1499.999756,12,28,185909.0,518.0,mode2,0,0,-3082.979248,4.511204,0.027479
1062910,8.191999,-0.371426,0.031594,194924560,7360.839844,11693983,4615.696777,0.987367,1499.999756,12,28,185909.0,518.0,mode2,0,0,-3115.697021,-11.752476,0.027679
1062911,8.195999,-0.284030,0.010178,194924590,7395.171875,11694001,4575.428711,1.000303,1499.999756,12,28,185909.0,518.0,mode2,0,0,-3075.428955,-27.878956,0.027716